# Place copy at: bin/pipelines/yaml/__PIPE__.yml
name: __PIPE__
version: 0.1
summary: Pipeline summary.
stages:
  - id: qc
    uses: modules/fastp
    with: { threads: 8 }
  - id: align
    uses: modules/bwa
    with: { threads: 16 }
env:
  # Optional wrapper env for the pipeline driver
  conda: envs/yaml/base.yml
