# Auto-generated by MAPI installer
export MAPI_ROOT="$HOME/MalariAPI"
export REMOTE_MAPI_HOME="$HOME/MalariAPI"
export REMOTE_SCRATCH="${REMOTE_SCRATCH:-/scratch/$USER/MalariAPI}"
export MAPI_SCRATCH="$MAPI_ROOT/scratch"
